### ISSUE TITLE
create account: validate that "username" is a valid email.

### ISSUE THREAD

**Issue by OhadR** [OhadR/authentication-flows#28]

**Comment by OhadR** [comment]
reopen: input as "a@" without domain is illengal. and get:
javax.mail.internet.AddressException: Invalid domain (a@,-1)
    at javax.mail.internet.AddressParser.illegalAddress(AddressParser.java:1126)
    at javax.mail.internet.AddressParser.validateDomain(AddressParser.java:1314)
    at javax.mail.internet.AddressParser.validateAddressSpec(AddressParser.java:1237)
    at javax.mail.internet.AddressParser.validateSimpleAddress(AddressParser.java:1
